Repository GoogleCloudPlatform/guest-agent, pull requests merged in 2019-10, with the labels that each got.

#2 add packaging scripts, linux configs
  90-google-guest-agent.preset
  go.mod
  go.sum
  google-guest-agent.conf
  google-guest-agent.service
  packaging/build_deb.sh
  packaging/build_goo.sh
  packaging/build_packages_wf.json
  packaging/build_rpm.sh
  packaging/common.sh
  packaging/daisy_startupscript_deb.sh
  packaging/daisy_startupscript_goo.sh
  packaging/daisy_startupscript_rpm.sh
  packaging/debian/changelog
  packaging/debian/compat
  packaging/debian/control
  packaging/debian/copyright
  packaging/debian/rules
  packaging/debian/source/format
  packaging/googet/agent_install.ps1
  packaging/googet/agent_uninstall.ps1
  packaging/googet/google-compute-engine-windows.goospec
  packaging/google-guest-agent.spec
Labels: approved, lgtm, size/XL

#5 add OWNERS
  OWNERS
Labels: approved, lgtm, size/S

#4 Enable all managers
  google_guest_agent/accounts.go
  google_guest_agent/main.go
  google_guest_agent/metadata.go
  google_guest_agent/oslogin.go
  packaging/build_deb.sh
Labels: approved, lgtm, size/M

#6 Add basic Windows instance setup for metadata route, fix issue with Windows addresses
  go.mod
  go.sum
  google_guest_agent/accounts_windows.go
  google_guest_agent/addresses.go
  google_guest_agent/addresses_unix.go
  google_guest_agent/addresses_windows.go
  google_guest_agent/instance_setup.go
  google_guest_agent/main.go
  google_guest_agent/non_windows_accounts.go
  google_guest_agent/stub.go
  google_guest_agent/system_windows.go
  google_guest_agent/windows_accounts.go
  packaging/common.sh
  packaging/debian/rules
  packaging/googet/agent_install.ps1
  packaging/googet/google-compute-engine-windows.goospec
Labels: approved, cla: yes, lgtm, size/XL

#8 Don't always set Admin group on reset password
  google_guest_agent/windows_accounts.go
Labels: approved, cla: yes, lgtm, size/XS
