Repository GoogleCloudPlatform/guest-agent, pull requests merged in 2019-12, with the labels that each got.

#13 Add rofuentes to OWNERS file.
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#12 restore diagnostics manager
  google_guest_agent/diagnostics.go
  google_guest_agent/diagnostics_test.go
  google_guest_agent/main.go
Labels: approved, cla: yes, lgtm, size/L

#10 Instance and boto configs
  google_guest_agent/instance_setup.go
  google_guest_agent/metadata.go
  instance_configs.cfg
  packaging/debian/postinst
  packaging/debian/postrm
  packaging/debian/rules
  packaging/google-guest-agent.spec
Labels: approved, cla: yes, lgtm, size/L

#14 Bump version to 20191204.00
  packaging/common.sh
  packaging/debian/changelog
Labels: approved, cla: yes, lgtm, size/XS

#15 Add addToAdministrators option for Windows accounts
  go.sum
  google_guest_agent/accounts_test.go
  google_guest_agent/metadata.go
  google_guest_agent/metadata_test.go
  google_guest_agent/windows_accounts.go
Labels: approved, cla: yes, lgtm, size/M

#16 Fixes from debugging sessions
  google_guest_agent/accounts_test.go
  google_guest_agent/accounts_unix.go
  google_guest_agent/addresses.go
  google_guest_agent/instance_setup.go
  google_guest_agent/main.go
  google_guest_agent/non_windows_accounts.go
  google_guest_agent/oslogin.go
Labels: approved, cla: yes, lgtm, size/L

#17 add Accounts:reuse_homedirs
  google_guest_agent/accounts_unix.go
  google_guest_agent/accounts_windows.go
  google_guest_agent/instance_setup.go
  google_guest_agent/non_windows_accounts.go
  google_guest_agent/oslogin.go
Labels: approved, cla: yes, lgtm, size/M
