Repository GoogleCloudPlatform/guest-agent, pull requests merged in 2020-08, with the labels that each got.

#66 oslogin: dont add entry to pam.d/su
  google_guest_agent/oslogin.go
  google_guest_agent/oslogin_test.go
Labels: approved, cla: yes, lgtm, size/M

#67 Correctly determine default route index
  google_guest_agent/instance_setup.go
Labels: approved, cla: yes, lgtm, size/XS

#68 Fix metric for addIPForwardEntry
  google_guest_agent/addresses_windows.go
  google_guest_agent/instance_setup.go
Labels: approved, cla: yes, lgtm, size/M

#69 add README
  README.md
Labels: approved, cla: yes, lgtm, size/L

#70 handle oslogin enable/disable cases
  google_guest_agent/non_windows_accounts.go
  google_guest_agent/oslogin.go
Labels: approved, cla: yes, lgtm, size/S

#71 Add all license files to packages
  THIRD_PARTY_LICENSES/cloud.google.com/go/LICENSE
  THIRD_PARTY_LICENSES/cloud.google.com/go/logging/LICENSE
  THIRD_PARTY_LICENSES/cloud.google.com/go/storage/LICENSE
  THIRD_PARTY_LICENSES/github.com/GoogleCloudPlatform/guest-agent/google_guest_agent/LICENSE
  THIRD_PARTY_LICENSES/github.com/GoogleCloudPlatform/guest-logging-go/logger/LICENSE
  THIRD_PARTY_LICENSES/github.com/go-ini/ini/LICENSE
  THIRD_PARTY_LICENSES/github.com/golang/groupcache/lru/LICENSE
  THIRD_PARTY_LICENSES/github.com/golang/protobuf/LICENSE
  THIRD_PARTY_LICENSES/github.com/google/go-cmp/cmp/LICENSE
  THIRD_PARTY_LICENSES/github.com/googleapis/gax-go/v2/LICENSE
  THIRD_PARTY_LICENSES/github.com/kardianos/service/LICENSE
  THIRD_PARTY_LICENSES/github.com/tarm/serial/LICENSE
  THIRD_PARTY_LICENSES/go.opencensus.io/LICENSE
  THIRD_PARTY_LICENSES/golang.org/x/net/LICENSE
  THIRD_PARTY_LICENSES/golang.org/x/oauth2/LICENSE
  THIRD_PARTY_LICENSES/golang.org/x/sync/semaphore/LICENSE
  THIRD_PARTY_LICENSES/golang.org/x/sys/LICENSE
  THIRD_PARTY_LICENSES/golang.org/x/text/LICENSE
  THIRD_PARTY_LICENSES/google.golang.org/api/LICENSE
  THIRD_PARTY_LICENSES/google.golang.org/genproto/LICENSE
  THIRD_PARTY_LICENSES/google.golang.org/grpc/LICENSE
  THIRD_PARTY_LICENSES/google.golang.org/protobuf/LICENSE
  go.mod
  packaging/debian/google-guest-agent.docs
  packaging/googet/google-compute-engine-metadata-scripts.goospec
  packaging/googet/google-compute-engine-windows.goospec
  packaging/google-guest-agent.spec
Labels: approved, cla: yes, lgtm, size/XXL
