Repository GoogleCloudPlatform/guest-agent, pull requests merged in 2020-12, with the labels that each got.

#92 Adding bkatyl to OWNERS
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#91 Adding support for Windows user account password lengths between 15 and 255 characters.
  google_guest_agent/accounts_test.go
  google_guest_agent/metadata.go
  google_guest_agent/windows_accounts.go
Labels: approved, cla: yes, lgtm, size/M

#90 Require snapshot scripts to live under /etc/google/snapshots
  google_guest_agent/snapshot_listener.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#94 set metadata URL earlier
  google_guest_agent/instance_setup.go
  google_guest_agent/main.go
Labels: approved, cla: yes, lgtm, size/XS
