Repository GoogleCloudPlatform/guest-agent, pull requests merged in 2020-07, with the labels that each got.

#62 fix typo in boto.cfg
  google_guest_agent/instance_setup.go
Labels: approved, cla: yes, lgtm, size/XS

#47 Set route to metadata on interface with default route
  google_guest_agent/instance_setup.go
  google_guest_agent/main.go
Labels: approved, cla: yes, lgtm, size/M

#59 Add source field in googet spec
  packaging/googet/google-compute-engine-metadata-scripts.goospec
  packaging/googet/google-compute-engine-windows.goospec
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#64 end group.conf with newline
  google_guest_agent/oslogin.go
  google_guest_agent/oslogin_test.go
Labels: approved, cla: yes, lgtm, size/XS
