Repository GoogleCloudPlatform/guest-agent, pull requests merged in 2020-01, with the labels that each got.

#18 Script runner
  go.mod
  google-shutdown-scripts.conf
  google-shutdown-scripts.service
  google-startup-scripts.conf
  google-startup-scripts.service
  google_metadata_script_runner/main.go
  google_metadata_script_runner/main_test.go
  packaging/debian/control
  packaging/debian/rules
  packaging/googet/google-compute-engine-metadata-scripts.goospec
  packaging/googet/metadata_scripts_install.ps1
  packaging/googet/metadata_scripts_uninstall.ps1
  packaging/googet/run_shutdown_scripts.cmd
  packaging/googet/run_startup_scripts.cmd
  packaging/google-guest-agent.spec
Labels: approved, cla: yes, lgtm, size/XL

#19 wait on metadata indefinitely
  go.mod
  go.sum
  google_guest_agent/instance_setup.go
  google_guest_agent/main.go
Labels: approved, cla: yes, lgtm, size/L

#21 enable non-GCE running
  LICENSE
  go.mod
  go.sum
  google-guest-agent.service
  google_guest_agent/instance_setup.go
Labels: approved, cla: yes, lgtm, size/M

#20 Instance config
  google_guest_agent/addresses.go
  google_guest_agent/non_windows_accounts.go
  google_guest_agent/wsfc.go
  instance_configs.cfg
Labels: approved, cla: yes, lgtm, size/M

#23 only use network-online.target
  google-guest-agent.service
Labels: approved, cla: yes, lgtm, size/XS

#24 Prevent GCEAgent from hanging on startup
  google_guest_agent/main.go
Labels: approved, cla: yes, lgtm, size/M

#25 Fix upstart,selinux
  google-guest-agent.conf
  google_guest_agent/instance_setup.go
  google_guest_agent/non_windows_accounts.go
Labels: approved, cla: yes, lgtm, size/XS

#27 revert service grouping
  google_guest_agent/oslogin.go
Labels: approved, cla: yes, lgtm, size/S
