Repository GoogleCloudPlatform/guest-agent, pull requests merged in 2020-10, with the labels that each got.

#81 getPasswd: Check full prefix of line for username
  google_guest_agent/non_windows_accounts.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#82 fallback to IP for metadata
  google_guest_agent/instance_setup.go
  google_guest_agent/metadata.go
Labels: approved, cla: yes, lgtm, size/S

#86 remove old unused workflow files
  packaging/build_deb.sh
  packaging/build_goo.sh
  packaging/build_packages_wf.json
  packaging/build_rpm.sh
  packaging/common.sh
  packaging/daisy_startupscript_deb.sh
  packaging/daisy_startupscript_goo.sh
  packaging/daisy_startupscript_rpm.sh
Labels: approved, cla: yes, lgtm, size/XL
