Repository GoogleCloudPlatform/guest-agent, pull requests merged in 2020-04, with the labels that each got.

#34 Fix issue with not using snapshot config
  google_guest_agent/instance_setup.go
  google_guest_agent/main.go
  google_guest_agent/snapshot_listener.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#35 Update Windows service configuration
  packaging/googet/agent_install.ps1
Labels: approved, cla: yes, lgtm, size/S

#37 Add configurable override for SSH hostkey directory
  google_guest_agent/instance_setup.go
Labels: approved, cla: yes, lgtm, size/XS

#36 correct SSH key handling
  google_guest_agent/accounts_test.go
  google_guest_agent/non_windows_accounts.go
Labels: approved, cla: yes, lgtm, size/S

#39 trim leading whitespace on inline scripts
  google_metadata_script_runner/main.go
Labels: approved, cla: yes, lgtm, size/XS
