Repository GoogleCloudPlatform/guest-agent, pull requests merged in 2021-04, with the labels that each got.

#105 Update error message for handleHealthCheckRequest
  google_guest_agent/wsfc.go
Labels: approved, cla: yes, lgtm, size/XS

#104 Restart the agent when systemd-networkd.service is restarted.
  google-guest-agent.service
Labels: approved, cla: yes, lgtm, size/S

#106 start sshd
  google_guest_agent/non_windows_accounts.go
  google_guest_agent/oslogin.go
Labels: approved, cla: yes, lgtm, size/M
