Repository GoogleCloudPlatform/guest-agent, pull requests merged in 2021-11, with the labels that each got.

#143 Integration tests: instance setup
  google_guest_agent/instance_setup_integ_test.go
  google_guest_agent/non_windows_accounts_integ_test.go
Labels: lgtm, approved, cla: yes, size/L

#145 dhcpv6 only as needed
  google_guest_agent/addresses.go
Labels: lgtm, approved, cla: yes, size/XS

#136 Add WantedBy network dependencies to google-guest-agent service
  google-guest-agent.service
Labels: lgtm, approved, cla: yes, size/XS, needs-ok-to-test

#146 dont duplicate logs
  google-guest-agent.service
  google-shutdown-scripts.service
  google-startup-scripts.service
Labels: lgtm, approved, cla: yes, size/XS
