Repository GoogleCloudPlatform/guest-agent, pull requests merged in 2022-05, with the labels that each got.

#165 Support .exe as an option for scripts and refactor runScript
  google_metadata_script_runner/main.go
  google_metadata_script_runner/main_test.go
Labels: lgtm, approved, size/L

#166 restore double slash metadata url
  google_guest_agent/metadata.go
Labels: lgtm, approved, size/XS

#164 Support for Windows SSH
  google_authorized_keys/main.go
  google_authorized_keys/main_test.go
  google_guest_agent/main.go
  google_guest_agent/metadata.go
  google_guest_agent/stub.go
  google_guest_agent/system_windows.go
  google_guest_agent/windows_accounts.go
  google_guest_agent/windows_accounts_test.go
  google_metadata_script_runner/main.go
  utils/main.go
Labels: size/XL, lgtm, approved

#167 Add authorized keys command to the Windows agent package.
  google_authorized_keys/main.go
  packaging/googet/google-compute-engine-windows.goospec
  packaging/googet/windows_agent_build.sh
Labels: lgtm, approved, size/S
