Repository GoogleCloudPlatform/guest-agent, pull requests merged in 2023-08, with the labels that each got.

#242 sshtrustedca watcher: fix concurrency error
  google_guest_agent/events/sshtrustedca/sshtrustedca.go
  google_guest_agent/events/sshtrustedca/sshtrustedca_linux.go
  google_guest_agent/events/sshtrustedca/sshtrustedca_linux_test.go
  google_guest_agent/main.go
Labels: lgtm, approved, size/M

#243 Add support for reading UEFI variables on windows
  google_guest_agent/agentcrypto/mtls_mds.go
  google_guest_agent/uefi/uefi.go
  google_guest_agent/uefi/uefi_unix.go
  google_guest_agent/uefi/uefi_unix_test.go
  google_guest_agent/uefi/uefi_windows.go
Labels: lgtm, approved, size/L

#246 sshca: transform the format from json to openssh
  google_guest_agent/main.go
Labels: lgtm, approved, size/S

#244 Add scheduler utility to run jobs at defined interval
  go.mod
  go.sum
  google_guest_agent/agentcrypto/mtls_mds.go
  google_guest_agent/agentcrypto/mtls_mds_test.go
  utils/scheduler/logger.go
  utils/scheduler/scheduler.go
  utils/scheduler/scheduler_test.go
Labels: size/XL, lgtm, approved

#249 Move scheduler package to google_guest_agent
  google_guest_agent/scheduler/logger.go
  google_guest_agent/scheduler/scheduler.go
  google_guest_agent/scheduler/scheduler_test.go
Labels: lgtm, approved, size/XS

#247 sshca: move the event handler to its own package
  google_guest_agent/events/events.go
  google_guest_agent/events/events_test.go
  google_guest_agent/main.go
  google_guest_agent/sshca/sshca.go
Labels: lgtm, approved, size/L

#248 Run telemetry every 24 hours, record pretty name on linux
  google_guest_agent/main.go
  google_guest_agent/osinfo/osinfo_unix.go
  google_guest_agent/osinfo/osinfo_unix_test.go
  google_guest_agent/telemetry/telemetry.go
Labels: lgtm, approved, size/L

#251 Update license files for guest-agent
  THIRD_PARTY_LICENSES/cloud.google.com/go/compute/metadata/LICENSE
  THIRD_PARTY_LICENSES/cloud.google.com/go/longrunning/LICENSE
  THIRD_PARTY_LICENSES/github.com/GoogleCloudPlatform/guest-agent/LICENSE
  THIRD_PARTY_LICENSES/github.com/google/go-sev-guest/LICENSE
  THIRD_PARTY_LICENSES/github.com/google/go-tpm-tools/LICENSE
  THIRD_PARTY_LICENSES/github.com/google/go-tpm/LICENSE
  THIRD_PARTY_LICENSES/github.com/google/logger/LICENSE
  THIRD_PARTY_LICENSES/github.com/google/s2a-go/LICENSE.md
  THIRD_PARTY_LICENSES/github.com/google/tink/go/LICENSE
  THIRD_PARTY_LICENSES/github.com/google/uuid/LICENSE
  THIRD_PARTY_LICENSES/github.com/googleapis/enterprise-certificate-proxy/client/LICENSE
  THIRD_PARTY_LICENSES/github.com/pborman/uuid/LICENSE
  THIRD_PARTY_LICENSES/github.com/pkg/errors/LICENSE
  THIRD_PARTY_LICENSES/github.com/robfig/cron/v3/LICENSE
  THIRD_PARTY_LICENSES/golang.org/x/crypto/LICENSE
  THIRD_PARTY_LICENSES/google.golang.org/api/internal/third_party/uritemplates/LICENSE
  THIRD_PARTY_LICENSES/google.golang.org/appengine/LICENSE
  THIRD_PARTY_LICENSES/google.golang.org/genproto/googleapis/LICENSE
  THIRD_PARTY_LICENSES/google.golang.org/genproto/googleapis/api/LICENSE
  THIRD_PARTY_LICENSES/google.golang.org/genproto/googleapis/rpc/LICENSE
  THIRD_PARTY_LICENSES/google.golang.org/grpc/NOTICE.txt
Labels: lgtm, approved, size/XXL

#254 Scheduler fixes
  google_guest_agent/main.go
  google_guest_agent/scheduler/scheduler.go
  google_guest_agent/scheduler/scheduler_test.go
Labels: lgtm, approved, size/L

#250 events: multiplex event watchers
  google_guest_agent/events/events.go
  google_guest_agent/events/events_test.go
  google_guest_agent/events/metadata/metadata.go
  google_guest_agent/events/sshtrustedca/sshtrustedca.go
  google_guest_agent/events/sshtrustedca/sshtrustedca_linux.go
  google_guest_agent/events/sshtrustedca/sshtrustedca_linux_test.go
  google_guest_agent/events/sshtrustedca/sshtrustedca_windows.go
Labels: lgtm, approved, size/L

#256 sshtrustedca: configure selinux context for sshtrustedca pipe
  google_guest_agent/events/events.go
  google_guest_agent/events/sshtrustedca/sshtrustedca.go
  google_guest_agent/events/sshtrustedca/sshtrustedca_linux.go
  google_guest_agent/events/sshtrustedca/sshtrustedca_linux_test.go
Labels: lgtm, approved, size/M

#257 Add pkcs12 license and update retry logic
  THIRD_PARTY_LICENSES/software.sslmate.com/src/go-pkcs12/LICENSE
  google_guest_agent/agentcrypto/mtls_mds.go
  google_guest_agent/main.go
  metadata/metadata.go
  metadata/metadata_test.go
Labels: lgtm, approved, size/L

#253 Enable telemetry collection by default
  README.md
  metadata/metadata.go
  metadata/metadata_test.go
Labels: lgtm, approved, size/S

#258 guest-agent: prepare for public release
  google_guest_agent/main.go
Labels: lgtm, approved, size/S

#259 Revert "guest-agent: prepare for public release (#258)"
  google_guest_agent/main.go
Labels: lgtm, approved, size/S

#261 Update owners.
  OWNERS
Labels: lgtm, approved, size/XS

#260 Update credentials directory on Linux
  google_guest_agent/agentcrypto/mtls_mds_linux.go
Labels: lgtm, approved, size/XS

#262 Revert "sshtrustedca: configure selinux context for sshtrustedca pipe…
  google_guest_agent/events/events.go
  google_guest_agent/events/sshtrustedca/sshtrustedca.go
  google_guest_agent/events/sshtrustedca/sshtrustedca_linux.go
  google_guest_agent/events/sshtrustedca/sshtrustedca_linux_test.go
Labels: lgtm, approved, size/M

#263 Find previous cert for cleanup using one stored on disk
  google_guest_agent/agentcrypto/crypto_util.go
  google_guest_agent/agentcrypto/crypto_util_test.go
  google_guest_agent/agentcrypto/mtls_mds.go
  google_guest_agent/agentcrypto/mtls_mds_windows.go
Labels: lgtm, approved, size/L

#264 confirm if cert was successfully added to certpool before verification
  google_guest_agent/agentcrypto/crypto_util.go
Labels: lgtm, approved, size/XS

#265 run: split command running utilities into its own package
  google_guest_agent/accounts_unix.go
  google_guest_agent/addresses.go
  google_guest_agent/clock.go
  google_guest_agent/instance_setup.go
  google_guest_agent/main.go
  google_guest_agent/non_windows_accounts.go
  google_guest_agent/oslogin.go
  google_guest_agent/run/run.go
  google_guest_agent/run/run_test.go
  google_guest_agent/snapshot_listener.go
  google_guest_agent/system_windows.go
Labels: lgtm, approved, size/L

#267 metadata watcher: remove local retry & implement unit tests
  google_guest_agent/events/metadata/metadata.go
  google_guest_agent/events/metadata/metadata_test.go
Labels: lgtm, approved, size/L

#269 Store certs in ProgramData instead of Program Files
  google_guest_agent/agentcrypto/mtls_mds.go
  google_guest_agent/agentcrypto/mtls_mds_linux.go
  google_guest_agent/agentcrypto/mtls_mds_windows.go
  utils/main.go
  utils/main_test.go
Labels: lgtm, approved, size/M
