Repository GoogleCloudPlatform/guest-agent, pull requests merged in 2023-11, with the labels that each got.

#327 Make config parsing order consistent
  google_metadata_script_runner/main.go
  google_metadata_script_runner/main_test.go
Labels: lgtm, approved, size/M

#328 Update owners.
  OWNERS
Labels: lgtm, approved, size/XS

#329 Update UEFI variable used for MDS cert
  google_guest_agent/agentcrypto/mtls_mds.go
Labels: lgtm, approved, size/XS

#331 Update script runner to use common cfg package
  google_metadata_script_runner/main.go
  google_metadata_script_runner/main_test.go
Labels: lgtm, approved, size/L

#333 revert: 3ddd9d4a496f7a9c591ded58c3f541fd9cc7e317
  google_guest_agent/cfg/cfg.go
  google_guest_agent/cfg/cfg_test.go
Labels: lgtm, approved, size/M

#334 sshca: remove certificate caching
  google_guest_agent/sshca/sshca.go
Labels: lgtm, approved, size/S
