Repository GoogleCloudPlatform/guest-agent, pull requests merged in 2023-07, with the labels that each got.

#217 snapshot: fix request handling error
  google_guest_agent/snapshot_listener.go
Labels: lgtm, approved, size/S

#218 metadata: moving to its own package
  .gitignore
  go.mod
  google_guest_agent/addresses.go
  google_guest_agent/addresses_test.go
  google_guest_agent/diagnostics.go
  google_guest_agent/diagnostics_test.go
  google_guest_agent/instance_setup.go
  google_guest_agent/main.go
  google_guest_agent/oslogin.go
  google_guest_agent/oslogin_test.go
  google_guest_agent/windows_accounts.go
  google_guest_agent/windows_accounts_test.go
  google_guest_agent/wsfc_test.go
  metadata/metadata.go
  metadata/metadata_test.go
  metadata/windows.go
Labels: lgtm, approved, size/L

#220 metadata: add metadata client interface
  google_guest_agent/diagnostics.go
  google_guest_agent/diagnostics_test.go
  google_guest_agent/instance_setup.go
  google_guest_agent/main.go
  google_guest_agent/oslogin.go
  google_guest_agent/windows_accounts_test.go
  metadata/metadata.go
  metadata/metadata_test.go
  metadata/windows.go
Labels: lgtm, approved, size/L

#221 events: introducing a events handling subsystem
  google_guest_agent/events/Readme.md
  google_guest_agent/events/events.go
  google_guest_agent/events/events_test.go
  google_guest_agent/events/metadata/metadata.go
Labels: size/XL, lgtm, approved

#223 events: start using events layer
  google_guest_agent/main.go
Labels: lgtm, approved, size/M

#222 sshTrustedCA: add pipe event handler
  google_guest_agent/.gitignore
  google_guest_agent/events/events.go
  google_guest_agent/events/sshtrustedca/sshtrustedca.go
  google_guest_agent/events/sshtrustedca/sshtrustedca_linux.go
  google_guest_agent/events/sshtrustedca/sshtrustedca_linux_test.go
  google_guest_agent/events/sshtrustedca/sshtrustedca_windows.go
Labels: lgtm, approved, size/L

#224 ssh_trusted_ca: enable the feature
  google_guest_agent/main.go
  google_guest_agent/oslogin.go
  google_guest_agent/oslogin_test.go
  metadata/metadata.go
Labels: lgtm, approved, size/M

#225 Support for reading & writing Root CA cert from UEFI variable
  google_guest_agent/agentcrypto/crypto_util.go
  google_guest_agent/agentcrypto/crypto_util_test.go
  google_guest_agent/agentcrypto/mtls_mds.go
  google_guest_agent/agentcrypto/mtls_mds_test.go
  google_guest_agent/uefi/uefi.go
  google_guest_agent/uefi/uefi_test.go
Labels: lgtm, approved, size/L

#227 metadata: pass main context to WriteGuestAttributes()
  google_guest_agent/addresses.go
  google_guest_agent/clock.go
  google_guest_agent/diagnostics.go
  google_guest_agent/instance_setup.go
  google_guest_agent/main.go
  google_guest_agent/non_windows_accounts.go
  google_guest_agent/oslogin.go
  google_guest_agent/windows_accounts.go
  google_guest_agent/wsfc.go
  google_guest_agent/wsfc_test.go
Labels: lgtm, approved, size/M

#226 Fetch guest credentials and MDS response proto
  go.mod
  go.sum
  google_guest_agent/agentcrypto/credentials/guest_credentials.pb.go
  google_guest_agent/agentcrypto/credentials/guest_credentials.proto
  google_guest_agent/agentcrypto/mtls_mds.go
  google_guest_agent/agentcrypto/mtls_mds_test.go
  google_guest_agent/fakes/fake_mds.go
  metadata/metadata.go
Labels: lgtm, approved, size/XXL

#228 Upgrade Go version 1.20
  go.mod
  go.sum
Labels: lgtm, approved, size/XXL

#230 Decrypt and store client credentials on disk
  go.mod
  go.sum
  google_guest_agent/agentcrypto/crypto_util.go
  google_guest_agent/agentcrypto/crypto_util_test.go
  google_guest_agent/agentcrypto/mtls_mds.go
Labels: lgtm, approved, size/L

#231 metadata: implement backoff strategy
  metadata/metadata.go
Labels: lgtm, approved, size/L

#232 metadata: remove the sleep around metadata in instance setup
  google_guest_agent/instance_setup.go
  metadata/metadata.go
Labels: lgtm, approved, size/XS

#233 metadata: fix context cancelation error check
  metadata/metadata.go
Labels: lgtm, approved, size/XS

#234 metadata: properly handle context cancelation
  metadata/metadata.go
Labels: lgtm, approved, size/S

#236 Verify client credentials are signed by root CA before writing on disk
  google_guest_agent/agentcrypto/crypto_util.go
  google_guest_agent/agentcrypto/crypto_util_test.go
  google_guest_agent/agentcrypto/mtls_mds.go
Labels: lgtm, approved, size/L

#235 metadata event handler: updates and bug fixes
  google_guest_agent/events/events.go
  google_guest_agent/events/events_test.go
  google_guest_agent/main.go
Labels: lgtm, approved, size/L

#219 Add (disabled) telemetry logic to GuestAgent
  google_guest_agent/addresses.go
  google_guest_agent/agentcrypto/mtls_mds.go
  google_guest_agent/fakes/fake_mds.go
  google_guest_agent/getrelease.go
  google_guest_agent/getrelease_test.go
  google_guest_agent/main.go
  google_guest_agent/osinfo/osinfo.go
  google_guest_agent/osinfo/osinfo_unix.go
  google_guest_agent/osinfo/osinfo_unix_test.go
  google_guest_agent/osinfo/osinfo_windows.go
  google_guest_agent/oslogin.go
  google_guest_agent/telemetry/proto/telemetry.pb.go
  google_guest_agent/telemetry/proto/telemetry.proto
  google_guest_agent/telemetry/telemetry.go
  google_guest_agent/telemetry/telemetry_test.go
  metadata/metadata.go
  metadata/metadata_test.go
Labels: lgtm, approved, size/XXL

#238 metadata: don't try to use metadata before agentInit() is done
  google_guest_agent/main.go
Labels: lgtm, approved, size/S

#239 main: bring back the mds client initialization
  google_guest_agent/main.go
Labels: lgtm, approved, size/XS

#240 metadata: properly set request config
  metadata/metadata.go
Labels: lgtm, approved, size/XS
