Repository GoogleCloudPlatform/guest-agent, pull requests merged in 2023-09, with the labels that each got.

#270 Notify systemd after scheduling required jobs
  google_guest_agent/instance_setup.go
  google_guest_agent/main.go
  google_guest_agent/scheduler/scheduler.go
  google_guest_agent/scheduler/scheduler_test.go
Labels: lgtm, approved, size/L

#268 run: change all commands to use CommandContext
  google_guest_agent/accounts_unix.go
  google_guest_agent/accounts_windows.go
  google_guest_agent/addresses.go
  google_guest_agent/clock.go
  google_guest_agent/diagnostics.go
  google_guest_agent/instance_setup.go
  google_guest_agent/non_windows_accounts.go
  google_guest_agent/oslogin.go
  google_guest_agent/run/run.go
  google_guest_agent/run/run_test.go
  google_guest_agent/stub.go
  google_guest_agent/system_windows.go
  google_guest_agent/windows_accounts.go
Labels: lgtm, approved, size/L

#271 restorecon: first try to determine if it's installed
  google_guest_agent/instance_setup.go
  google_guest_agent/non_windows_accounts.go
Labels: lgtm, approved, size/S

#272 Store keys to machine keyset
  google_guest_agent/agentcrypto/mtls_mds_windows.go
Labels: lgtm, approved, size/XS

#273 service: remove the use of the service library
  THIRD_PARTY_LICENSES/github.com/kardianos/service/LICENSE
  go.mod
  go.sum
  google_guest_agent/events/metadata/metadata.go
  google_guest_agent/main.go
  google_guest_agent/service.go
Labels: lgtm, approved, size/L

#276 Revert "service: remove the use of the service library (#273)"
  THIRD_PARTY_LICENSES/github.com/kardianos/service/LICENSE
  go.mod
  go.sum
  google_guest_agent/events/metadata/metadata.go
  google_guest_agent/main.go
  google_guest_agent/service.go
Labels: lgtm, approved, size/L

#280 New Guest Agent Release
  google_guest_agent/instance_setup.go
  google_guest_agent/main.go
Labels: lgtm, approved, size/XS

#281 release prep: disable ssh trusted ca module
  google_guest_agent/main.go
Labels: lgtm, approved, size/XS

#284 metadata: use url package to form metadata URLs
  metadata/metadata.go
Labels: lgtm, approved, size/M

#275 Update workload certificate endpoints, use metadata package
  gce_workload_cert_refresh/main.go
Labels: lgtm, approved, size/L

#278 Update system store
  google_guest_agent/agentcrypto/mtls_mds.go
  google_guest_agent/agentcrypto/mtls_mds_linux.go
  google_guest_agent/agentcrypto/mtls_mds_linux_test.go
  google_guest_agent/agentcrypto/mtls_mds_windows.go
  utils/main.go
  utils/main_test.go
Labels: lgtm, approved, size/L

#282 remove deprecated usage, fix warnings
  google_authorized_keys/main.go
  google_guest_agent/instance_setup.go
  google_guest_agent/instance_setup_integ_test.go
  google_guest_agent/non_windows_accounts.go
  google_guest_agent/osinfo/osinfo_unix.go
  google_guest_agent/oslogin.go
  google_guest_agent/snapshot_listener.go
  google_guest_agent/windows_accounts.go
  google_guest_agent/windows_accounts_test.go
  google_metadata_script_runner/main.go
Labels: lgtm, approved, size/M

#286 sshca: make sure to restore SELinux context of the pipe
  google_guest_agent/events/sshtrustedca/sshtrustedca_linux.go
Labels: lgtm, approved, size/S

#287 Preparing it for review
  CONTRIBUTING.md
  LICENSE
  google_guest_agent/fakes/fake_mds.go
  metadata/windows.go
  packaging/googet/windows_agent_build.sh
Labels: lgtm, approved, size/M

#285 oslogin: add PAMless Authorization Stack configuration
  google_guest_agent/oslogin.go
  google_guest_agent/oslogin_test.go
Labels: lgtm, approved, size/L

#289 sshca: re-enable the event watcher & handler
  google_guest_agent/main.go
  google_guest_agent/oslogin.go
Labels: lgtm, approved, size/XS

#291 Fix permissions on file created by SaferWriteFile()
  google_guest_agent/agentcrypto/mtls_mds_linux.go
  google_guest_agent/agentcrypto/mtls_mds_windows.go
  utils/main.go
  utils/main_test.go
Labels: lgtm, approved, size/M

#292 mtls: bring it back
  google_guest_agent/main.go
Labels: lgtm, approved, size/XS

#288 cfg: introduce a configuration management package
  google_guest_agent/accounts_unix.go
  google_guest_agent/addresses.go
  google_guest_agent/addresses_test.go
  google_guest_agent/cfg/cfg.go
  google_guest_agent/cfg/cfg_test.go
  google_guest_agent/clock.go
  google_guest_agent/diagnostics.go
  google_guest_agent/diagnostics_test.go
  google_guest_agent/instance_setup.go
  google_guest_agent/instance_setup_integ_test.go
  google_guest_agent/main.go
  google_guest_agent/non_windows_accounts.go
  google_guest_agent/oslogin.go
  google_guest_agent/snapshot_listener.go
  google_guest_agent/windows_accounts.go
  google_guest_agent/windows_accounts_test.go
  google_guest_agent/wsfc.go
  google_guest_agent/wsfc_test.go
Labels: lgtm, approved, size/XXL

#293 cfg: config typos
  google_guest_agent/cfg/cfg.go
Labels: lgtm, approved, size/XS

#294 cfg: fix typos
  google_guest_agent/cfg/cfg.go
Labels: lgtm, approved, size/XS

#295 managers: we accidentally disabled addressMgr, bring it back
  google_guest_agent/main.go
Labels: lgtm, approved, size/S

#297 gitignore: unify ignore in the root dir
  .gitignore
  google_guest_agent/.gitignore
Labels: lgtm, approved, size/XS

#298 oslogin: introduce a feature flag to cert auth
  google_guest_agent/cfg/cfg.go
  google_guest_agent/oslogin.go
  google_guest_agent/oslogin_test.go
  instance_configs.cfg
Labels: lgtm, approved, size/M

#299 oslogin: resort ssh configuration keys
  google_guest_agent/oslogin.go
  google_guest_agent/oslogin_test.go
Labels: lgtm, approved, size/S
