Repository GoogleCloudPlatform/guest-agent, pull requests merged in 2023-10, with the labels that each got.

#303 oslogin: remove Unstable.pamless_auth_stack feature flag
  google_guest_agent/cfg/cfg.go
  google_guest_agent/oslogin.go
  google_guest_agent/oslogin_test.go
Labels: lgtm, approved, size/L

#304 oslogin: declare explicitly dependency
  packaging/debian/control
  packaging/google-guest-agent.spec
Labels: lgtm, approved, size/XS

#305 packaging: force epoch and ignore suffix of version
  packaging/google-guest-agent.spec
Labels: lgtm, approved, size/XS

#306 packaging(deb): ignore suffix of version
  packaging/debian/control
Labels: lgtm, approved, size/XS

#308 Dependency update
  packaging/debian/control
Labels: lgtm, approved, size/XS

#309 docs update: add configuration and event manager's docs.
  README.md
  google_guest_agent/events/Readme.md
Labels: lgtm, approved, size/XS

#300 Refactor authorized keys to use metadata package
  google_authorized_keys/main.go
  google_authorized_keys/main_test.go
  google_guest_agent/events/metadata/metadata.go
  google_guest_agent/events/metadata/metadata_test.go
  google_guest_agent/fakes/fake_mds.go
  google_guest_agent/scheduler/scheduler_test.go
  metadata/metadata.go
  metadata/metadata_test.go
Labels: lgtm, approved, size/L

#310 Schedule MTLS job before notifying systemd
  google_guest_agent/instance_setup.go
  google_guest_agent/main.go
Labels: lgtm, approved, size/S

#311 Refactor script runner to use common metadata package
  google_metadata_script_runner/main.go
  google_metadata_script_runner/main_test.go
Labels: lgtm, approved, size/L

#290 Events interface improvement
  google_guest_agent/events/events.go
  google_guest_agent/events/events_test.go
  google_guest_agent/main.go
  google_guest_agent/oslogin.go
  google_guest_agent/sshca/sshca.go
Labels: size/XL, lgtm, approved

#296 Add support for the SSH key options
  go.mod
  go.sum
  google_authorized_keys/main_test.go
  google_guest_agent/non_windows_accounts.go
  google_guest_agent/windows_accounts_test.go
  utils/main.go
  utils/main_test.go
  utils/test.go
Labels: lgtm, approved, size/L, ok-to-test

#312 Verify cert refresher is enabled before running
  gce_workload_cert_refresh/main.go
Labels: lgtm, approved, size/M

#314 Update known cert dirs for updaters
  google_guest_agent/agentcrypto/mtls_mds_linux.go
  google_guest_agent/agentcrypto/mtls_mds_linux_test.go
Labels: lgtm, approved, size/M

#316 instance setup: trust/rely on metadata package's retry
  google_guest_agent/instance_setup.go
Labels: lgtm, approved, size/S

#318 snapshot: add context cancellation handling
  google_guest_agent/snapshot_listener.go
Labels: lgtm, approved, size/XS

#317 Don't try to schedule mTLS job twice
  google_guest_agent/main.go
Labels: lgtm, approved, size/XS

#315 Update response struct, add tests
  .gitignore
  gce_workload_cert_refresh/main.go
  gce_workload_cert_refresh/main_test.go
  go.mod
Labels: size/XL, lgtm, approved

#322 Remove previous MDS root certificate if refreshed
  google_guest_agent/agentcrypto/mtls_mds_windows.go
Labels: lgtm, approved, size/S

#323 Enable mTLS cred generation by default
  google_guest_agent/cfg/cfg.go
  google_guest_agent/instance_setup.go
Labels: lgtm, approved, size/S

#324 Test configuration files are loaded in the documented order. Fix initial integration test.
  google_guest_agent/cfg/cfg.go
  google_guest_agent/cfg/cfg_test.go
Labels: lgtm, approved, size/L
