Repository GoogleCloudPlatform/guest-agent, pull requests merged in 2024-11, with the labels that each got.

#464 Bring back side-by-side packaging to dev branch.
  packaging/debian/rules
  packaging/googet/agent_install.ps1
  packaging/googet/agent_uninstall.ps1
  packaging/google-guest-agent.spec
Labels: lgtm, approved, size/L

#466 Add missing packaging spec for windows build
  packaging/googet/google-compute-engine-windows.goospec
  packaging/googet/windows_agent_build.sh
Labels: lgtm, approved, size/S

#469 Update readme with guest agent manager
  README.md
Labels: lgtm, approved, size/XS

#472 network: fix nmcli check pattern
  google_guest_agent/network/manager/network_manager_linux.go
Labels: lgtm, approved, size/XS

#471 Fixing fallback from systemd-networkd to dhclient
  google_guest_agent/network/manager/systemd_networkd_linux.go
Labels: lgtm, approved, size/XS, ok-to-test

#474 stable/network: fix cliExists() call pattern
  google_guest_agent/network/manager/network_manager_linux.go
  google_guest_agent/network/manager/systemd_networkd_linux.go
Labels: lgtm, approved, size/XS
