Repository GoogleCloudPlatform/guest-agent, pull requests merged in 2024-02, with the labels that each got.

#348 Implement cleanup of deprecated configuration directives
  google_guest_agent/oslogin.go
Labels: lgtm, approved, size/M

#353 Don't override version on metadata script runner with hardcoded constant
  google_metadata_script_runner/main.go
Labels: lgtm, approved, size/XS

#350 Implement retry util
  retry/retry.go
  retry/retry_test.go
Labels: lgtm, approved, size/L

#351 Update manager tests, Create DHClient unit tests.
  google_guest_agent/network/manager/common.go
  google_guest_agent/network/manager/dhclient_linux.go
  google_guest_agent/network/manager/dhclient_linux_test.go
  google_guest_agent/network/manager/manager.go
  google_guest_agent/network/manager/manager_test.go
  google_guest_agent/network/manager/systemd_networkd_linux.go
  google_guest_agent/ps/ps.go
  google_guest_agent/ps/ps_linux.go
  google_guest_agent/run/run.go
Labels: lgtm, approved, size/XXL

#354 Create systemd-networkd unit tests
  google_guest_agent/network/manager/systemd_networkd_linux.go
  google_guest_agent/network/manager/systemd_networkd_linux_test.go
Labels: size/XL, lgtm, approved

#359 Flush logs before exiting
  gce_workload_cert_refresh/main.go
  google_authorized_keys/main.go
  google_guest_agent/main.go
  google_metadata_script_runner/main.go
Labels: lgtm, approved, size/S

#355 Refactor guest-agent to use common retry util
  google_guest_agent/instance_setup.go
  google_guest_agent/oslogin.go
  metadata/metadata.go
  metadata/metadata_test.go
Labels: lgtm, approved, size/L

#357 Update metadata script runner to use retry util, add unit tests
  google_metadata_script_runner/main.go
  google_metadata_script_runner/main_test.go
Labels: lgtm, approved, size/L

#356 Create wicked network service implementation and its respective unit tests
  google_guest_agent/network/manager/manager.go
  google_guest_agent/network/manager/systemd_networkd_linux_test.go
  google_guest_agent/network/manager/wicked_linux.go
  google_guest_agent/network/manager/wicked_linux_test.go
Labels: size/XL, lgtm, approved

#360 network: remove ignore setup
  google_guest_agent/network/manager/manager.go
Labels: lgtm, approved, size/XS

#363 Skip interface manager on Windows
  go.mod
  go.sum
  google_guest_agent/addresses.go
Labels: lgtm, approved, size/S

#362 Create NetworkManager implementation
  google_guest_agent/network/manager/manager.go
  google_guest_agent/network/manager/manager_test.go
  google_guest_agent/network/manager/network_manager_linux.go
  google_guest_agent/network/manager/network_manager_linux_test.go
  google_guest_agent/network/manager/systemd_networkd_linux.go
  google_guest_agent/network/manager/systemd_networkd_linux_test.go
Labels: size/XL, lgtm, approved

#366 Check for nil response
  metadata/metadata.go
Labels: lgtm, approved, size/XS

#361 Dynamic vlan
  google_guest_agent/addresses.go
  google_guest_agent/cfg/cfg.go
  google_guest_agent/network/manager/common.go
  google_guest_agent/network/manager/common_test.go
  google_guest_agent/network/manager/dhclient_linux.go
  google_guest_agent/network/manager/dhclient_linux_test.go
  google_guest_agent/network/manager/manager.go
  google_guest_agent/network/manager/manager_test.go
  google_guest_agent/network/manager/network_manager_linux.go
  google_guest_agent/network/manager/systemd_networkd_linux.go
  google_guest_agent/network/manager/systemd_networkd_linux_test.go
  google_guest_agent/network/manager/wicked_linux.go
  google_guest_agent/network/manager/wicked_linux_test.go
  google_guest_agent/run/run.go
  google_guest_agent/run/run_test.go
  metadata/metadata.go
  utils/regex.go
  utils/regex_test.go
Labels: lgtm, approved, size/XXL
