Repository GoogleCloudPlatform/guest-agent, pull requests merged in 2024-06, with the labels that each got.

#398 oslogin: don't remove sshca watcher when oslogin is disabled
  google_guest_agent/oslogin.go
Labels: lgtm, approved, size/XS

#396 Network subsystem remove os rules
  google_guest_agent/network/manager/common.go
  google_guest_agent/network/manager/dhclient_linux.go
  google_guest_agent/network/manager/manager.go
  google_guest_agent/network/manager/manager_linux.go
  google_guest_agent/network/manager/manager_test.go
  google_guest_agent/network/manager/netplan_linux.go
  google_guest_agent/network/manager/network_manager_linux.go
  google_guest_agent/network/manager/systemd_networkd_linux.go
  google_guest_agent/network/manager/wicked_linux.go
  metadata/metadata.go
Labels: lgtm, approved, size/L

#399 Enabling logging in google-startup-script.service
  google-startup-scripts.service
Labels: lgtm, approved, size/XS, needs-ok-to-test
