Repository GoogleCloudPlatform/guest-agent, pull requests merged in 2024-07, with the labels that each got.

#403 Update Accounts documentation
  README.md
Labels: lgtm, approved, size/S

#404 Add ipv6 support to forward ips in guest agent
  google_guest_agent/addresses.go
  google_guest_agent/addresses_test.go
  google_guest_agent/addresses_unix.go
  google_guest_agent/addresses_windows.go
Labels: lgtm, approved, size/L

#405 Skip root cert rotation if installed once
  google_guest_agent/agentcrypto/mtls_mds.go
Labels: lgtm, approved, size/M

#400 Disable OS Login without pruning off any extra suffix.
  google_guest_agent/oslogin.go
  google_guest_agent/oslogin_test.go
Labels: lgtm, approved, size/S

#407 Only release dhclient leases for an interface if the respective dhclient is still running
  google_guest_agent/network/manager/dhclient_linux.go
Labels: lgtm, approved, size/S

#402 Update NIC management strategy
  README.md
  google_guest_agent/cfg/cfg.go
  google_guest_agent/instance_setup.go
  google_guest_agent/network/manager/dhclient_linux.go
  google_guest_agent/network/manager/dhclient_linux_test.go
  google_guest_agent/network/manager/manager.go
  google_guest_agent/network/manager/manager_linux.go
  google_guest_agent/network/manager/manager_test.go
  google_guest_agent/network/manager/netplan_linux.go
  google_guest_agent/network/manager/network_manager_linux.go
  google_guest_agent/network/manager/wicked_linux.go
Labels: lgtm, approved, size/L
