Repository GoogleCloudPlatform/guest-agent, pull requests merged in 2024-09, with the labels that each got.

#426 Adapt and update mtls mds config key to be consistent with MDS
  README.md
  google_guest_agent/agentcrypto/mtls_mds.go
  google_guest_agent/agentcrypto/mtls_mds_linux_test.go
  google_guest_agent/cfg/cfg.go
  metadata/metadata.go
Labels: lgtm, approved, size/L

#424 Revert "Config to disable the use of OS native cert stores "
  google_guest_agent/agentcrypto/mtls_mds_linux.go
  google_guest_agent/agentcrypto/mtls_mds_linux_test.go
  google_guest_agent/agentcrypto/mtls_mds_windows.go
  google_guest_agent/cfg/cfg.go
Labels: lgtm, approved, size/S

#413 Introduce a configuration toggle for enabling/disabling cloud logging
  README.md
  google_guest_agent/cfg/cfg.go
  google_guest_agent/main.go
Labels: lgtm, approved, size/S

#425 Port changes from #383, #413 to stable branch
  google_guest_agent/cfg/cfg.go
  google_guest_agent/main.go
  metadata/metadata.go
Labels: lgtm, approved, size/M

#427 Update README to reflect new network manager changes
  README.md
Labels: lgtm, approved, size/M

#428 Fix debian12 netplan config issue, use ptr receiver
  google_guest_agent/network/manager/dhclient_linux.go
  google_guest_agent/network/manager/netplan_linux.go
  google_guest_agent/network/manager/network_manager_linux.go
  google_guest_agent/network/manager/systemd_networkd_linux.go
  google_guest_agent/network/manager/wicked_linux.go
Labels: lgtm, approved, size/L

#429 Add VLAN NIC support for NetworkManager
  google_guest_agent/network/manager/manager.go
  google_guest_agent/network/manager/network_manager_linux.go
  google_guest_agent/network/manager/network_manager_linux_test.go
  google_guest_agent/network/manager/systemd_networkd_linux_test.go
Labels: lgtm, approved, size/L

#430 Fix panics in agent when setting up VLAN with netplan
  google_guest_agent/network/manager/common.go
  google_guest_agent/network/manager/common_test.go
  google_guest_agent/network/manager/netplan_linux.go
  google_guest_agent/network/manager/netplan_linux_test.go
  metadata/metadata.go
Labels: size/XL, lgtm, approved

#431 Update Vlan interfaces format to match with MDS
  google_guest_agent/network/manager/common.go
  google_guest_agent/network/manager/common_test.go
  google_guest_agent/network/manager/dhclient_linux.go
  google_guest_agent/network/manager/manager.go
  google_guest_agent/network/manager/manager_test.go
  google_guest_agent/network/manager/netplan_linux.go
  google_guest_agent/network/manager/netplan_linux_test.go
  google_guest_agent/network/manager/network_manager_linux.go
  google_guest_agent/network/manager/network_manager_linux_test.go
  google_guest_agent/network/manager/systemd_networkd_linux.go
  google_guest_agent/network/manager/systemd_networkd_linux_test.go
  google_guest_agent/network/manager/wicked_linux.go
  metadata/metadata.go
  metadata/metadata_test.go
Labels: size/XL, lgtm, approved

#432 network: remove primary NIC left over configs.
  google_guest_agent/network/manager/dhclient_linux.go
  google_guest_agent/network/manager/manager.go
  google_guest_agent/network/manager/manager_test.go
  google_guest_agent/network/manager/netplan_linux.go
  google_guest_agent/network/manager/network_manager_linux.go
  google_guest_agent/network/manager/systemd_networkd_linux.go
  google_guest_agent/network/manager/wicked_linux.go
Labels: lgtm, approved, size/L

#433 network: restore debian-12 netplan configuration.
  README.md
  google_guest_agent/cfg/cfg.go
  google_guest_agent/network/manager/manager.go
Labels: lgtm, approved, size/M

#434 Change mtls mds defaults, update log message to assure error is harmless
  google_guest_agent/agentcrypto/mtls_mds.go
  google_guest_agent/agentcrypto/mtls_mds_linux_test.go
  google_guest_agent/cfg/cfg.go
Labels: lgtm, approved, size/S

#436 network: debian 12 rollback only if default netplan is ok
  google_guest_agent/network/manager/manager.go
Labels: lgtm, approved, size/M
