Repository GoogleCloudPlatform/guest-agent, pull requests merged in 2024-01, with the labels that each got.

#339 Update licenses with dependencies of go-winio
  THIRD_PARTY_LICENSES/github.com/hashicorp/hcl/LICENSE
  THIRD_PARTY_LICENSES/github.com/mitchellh/go-homedir/LICENSE
  THIRD_PARTY_LICENSES/golang.org/x/mod/LICENSE
  THIRD_PARTY_LICENSES/golang.org/x/tools/LICENSE
Labels: lgtm, approved, size/L

#343 Delete integration tests
  google_guest_agent/addresses_integ_test.go
  google_guest_agent/instance_setup_integ_test.go
  google_guest_agent/non_windows_accounts_integ_test.go
Labels: lgtm, approved, size/L

#345 Remove quintonamore from OWNERS
  OWNERS
Labels: lgtm, approved, size/XS

#346 Generate windows and linux licenses
  THIRD_PARTY_LICENSES/cloud.google.com/go/iam/LICENSE
  THIRD_PARTY_LICENSES/cloud.google.com/go/internal/LICENSE
  THIRD_PARTY_LICENSES/github.com/GoogleCloudPlatform/guest-agent/LICENSE
  THIRD_PARTY_LICENSES/github.com/GoogleCloudPlatform/guest-agent/google_guest_agent/LICENSE
  THIRD_PARTY_LICENSES/github.com/hashicorp/hcl/LICENSE
  THIRD_PARTY_LICENSES/github.com/mitchellh/go-homedir/LICENSE
  THIRD_PARTY_LICENSES/golang.org/x/tools/LICENSE
  THIRD_PARTY_LICENSES/golang.org/x/xerrors/LICENSE
  THIRD_PARTY_LICENSES/software.sslmate.com/src/go-pkcs12/LICENSE
  packaging/genlicense.sh
Labels: size/XL, lgtm, approved

#342 Deprecate DHClient in favor of systemd-networkd
  google_guest_agent/addresses.go
  google_guest_agent/network/manager/common.go
  google_guest_agent/network/manager/dhclient_linux.go
  google_guest_agent/network/manager/manager.go
  google_guest_agent/network/manager/manager_test.go
  google_guest_agent/network/manager/systemd_networkd_linux.go
  google_guest_agent/ps/ps.go
  google_guest_agent/ps/ps_linux.go
  google_guest_agent/ps/ps_linux_test.go
  google_guest_agent/ps/ps_windows.go
Labels: lgtm, approved, size/XXL

#347 ignore DHCP offered routes only for secondary nics
  google_guest_agent/network/manager/systemd_networkd_linux.go
Labels: lgtm, approved, size/S
