Repository GoogleCloudPlatform/guest-agent, pull requests merged in 2024-08, with the labels that each got.

#408 Configure primary nic if only set in cfg file
  google_guest_agent/network/manager/netplan_linux.go
Labels: lgtm, approved, size/S

#409 Fix where agent panics on nil event in sshca watcher
  google_guest_agent/events/sshtrustedca/sshtrustedca_linux.go
  google_guest_agent/sshca/sshca.go
Labels: lgtm, approved, size/S

#411 Get rid of deprecated dependencies in snapshot service
  go.mod
  google_guest_agent/snapshot_listener.go
  google_guest_agent/snapshot_service/cloud_vmm/snapshot_service.pb.go
  google_guest_agent/snapshot_service/cloud_vmm/snapshot_service_grpc.pb.go
  google_guest_agent/snapshot_service/snapshot_service.proto
  google_guest_agent/snapshot_service/snapshot_service.proto.pb.go
Labels: lgtm, approved, size/XXL

#412 Update golang.org/x/net dependencies to catch up on CVEs
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#415 Fix dependencies in stable branch #412
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#410 Avoid writing configuration files when they already exist on wicked and NetworkManager
  google_guest_agent/network/manager/netplan_linux.go
  google_guest_agent/network/manager/network_manager_linux.go
  google_guest_agent/network/manager/wicked_linux.go
Labels: lgtm, approved, size/M

#418 Update README with MDS MTLS docs
  README.md
Labels: lgtm, approved, size/M

#419 Config to disable the use of OS native cert stores
  google_guest_agent/agentcrypto/mtls_mds_linux.go
  google_guest_agent/agentcrypto/mtls_mds_linux_test.go
  google_guest_agent/agentcrypto/mtls_mds_windows.go
  google_guest_agent/cfg/cfg.go
Labels: lgtm, approved, size/S

#421 Document disabling account manager on AD
  README.md
Labels: lgtm, approved, size/S

#422 Make primary nic management config consistent across all network managers
  google_guest_agent/network/manager/dhclient_linux.go
  google_guest_agent/network/manager/netplan_linux.go
  google_guest_agent/network/manager/network_manager_linux.go
  google_guest_agent/network/manager/systemd_networkd_linux.go
  google_guest_agent/network/manager/wicked_linux.go
Labels: lgtm, approved, size/M

#423 Allow users to enable/disable the mds mtls via metadata key
  README.md
  google_guest_agent/agentcrypto/mtls_mds.go
  google_guest_agent/agentcrypto/mtls_mds_linux.go
  google_guest_agent/agentcrypto/mtls_mds_linux_test.go
  google_guest_agent/agentcrypto/mtls_mds_windows.go
  google_guest_agent/cfg/cfg.go
  google_guest_agent/instance_setup.go
  google_guest_agent/scheduler/scheduler.go
  google_guest_agent/scheduler/scheduler_test.go
  metadata/metadata.go
Labels: lgtm, approved, size/L
