Repository GoogleCloudPlatform/guest-agent, pull requests merged in 2024-10, with the labels that each got.

#437 Log interface state after setting up network
  google_guest_agent/network/manager/common.go
  google_guest_agent/network/manager/manager.go
Labels: lgtm, approved, size/S

#438 Retry MDS PUT operation, reload netplan/networkctl only if configs are changed
  google_guest_agent/network/manager/common.go
  google_guest_agent/network/manager/dhclient_linux.go
  google_guest_agent/network/manager/manager.go
  google_guest_agent/network/manager/netplan_linux.go
  google_guest_agent/network/manager/network_manager_linux.go
  google_guest_agent/network/manager/network_manager_linux_test.go
  google_guest_agent/network/manager/systemd_networkd_linux.go
  google_guest_agent/network/manager/systemd_networkd_linux_test.go
  metadata/metadata.go
Labels: lgtm, approved, size/L

#439 Repeated logging could be mistaken for a recurring issue, log mds mtls endpoint error only once
  google_guest_agent/agentcrypto/mtls_mds.go
Labels: lgtm, approved, size/S

#444 Skip SetupInterfaces if network configs are already applied
  google_guest_agent/network/manager/manager.go
Labels: lgtm, approved, size/S

#445 network/netplan: do generate instead of apply
  google_guest_agent/network/manager/netplan_linux.go
  google_guest_agent/network/manager/netplan_linux_test.go
Labels: lgtm, approved, size/S

#446 Avoid unnecessary reloads, check before overwriting configs
  google_guest_agent/network/manager/common.go
  google_guest_agent/network/manager/common_test.go
  google_guest_agent/network/manager/manager_linux.go
  google_guest_agent/network/manager/netplan_linux.go
  google_guest_agent/network/manager/netplan_linux_test.go
Labels: lgtm, approved, size/L

#448 Revert "network/netplan: adjust link-local accordingly (#443)"
  google_guest_agent/network/manager/netplan_linux.go
Labels: lgtm, approved, size/XS

#450 Skip MDS setup by default for this release
  google_guest_agent/agentcrypto/mtls_mds_linux_test.go
  google_guest_agent/cfg/cfg.go
Labels: lgtm, approved, size/XS

#451 SUSE no overwrite bug fix, ubuntu 18.04 exception
  README.md
  google_guest_agent/network/manager/common.go
  google_guest_agent/network/manager/dhclient_linux.go
  google_guest_agent/network/manager/netplan_linux.go
  google_guest_agent/network/manager/wicked_linux.go
  google_guest_agent/network/manager/wicked_linux_test.go
Labels: lgtm, approved, size/M

#452 Update OWNERS
  OWNERS
Labels: lgtm, approved, size/XS

#453 documentation: update metadata script runner details
  README.md
Labels: lgtm, approved, size/XS

#455 plugin manager: introduce the systemd service file
  google-guest-agent-manager.service
Labels: lgtm, approved, size/S

#456 Add support for including agent manager in guest-agent package
  packaging/googet/agent_install.ps1
  packaging/googet/agent_uninstall.ps1
  packaging/googet/google-compute-engine-windows.goospec
  packaging/googet/windows_agent_build.sh
Labels: lgtm, approved, size/M

#454 packaging: add plugin manager to rhel packaging
  packaging/google-guest-agent.spec
Labels: lgtm, approved, size/M

#458 rpm packaging: fix plugin manager assumptions
  packaging/google-guest-agent.spec
Labels: lgtm, approved, size/S

#457 Add plugin manager to debian build
  packaging/debian/control
  packaging/debian/rules
Labels: lgtm, approved, size/S

#459 Add GOPATH to PATH in debian build
  packaging/debian/control
  packaging/debian/rules
Labels: lgtm, approved, size/XS

#460 Revert plugin manager packaging
  packaging/debian/rules
  packaging/googet/agent_install.ps1
  packaging/googet/agent_uninstall.ps1
  packaging/googet/google-compute-engine-windows.goospec
  packaging/googet/windows_agent_build.sh
  packaging/google-guest-agent.spec
Labels: lgtm, approved, size/L

#463 Avoid changing permissions of directory if parent is /
  google_guest_agent/command/command_linux.go
Labels: lgtm, approved, size/M
