Repository GoogleCloudPlatform/guest-agent, pull requests merged in 2024-05, with the labels that each got.

#388 Log current available routes on error
  google_guest_agent/accounts_windows.go
  google_guest_agent/instance_setup.go
Labels: lgtm, approved, size/S

#391 update dependencies to catch up on CVE fixes
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#386 Network manager netplan implementation
  go.mod
  go.sum
  google_guest_agent/network/manager/common.go
  google_guest_agent/network/manager/dhclient_linux.go
  google_guest_agent/network/manager/manager.go
  google_guest_agent/network/manager/manager_test.go
  google_guest_agent/network/manager/netplan_linux.go
  google_guest_agent/network/manager/network_manager_linux.go
  google_guest_agent/network/manager/network_manager_linux_test.go
  google_guest_agent/network/manager/systemd_networkd_linux.go
  google_guest_agent/network/manager/systemd_networkd_linux_test.go
Labels: size/XL, lgtm, approved
