Repository GoogleCloudPlatform/guest-agent, pull requests merged in 2024-03, with the labels that each got.

#369 oslogin: avoid adding extra empty line at the end of /etc/security/gr…
  google_guest_agent/oslogin.go
  google_guest_agent/oslogin_test.go
Labels: lgtm, approved, size/XS

#371 Network Manager: make sure we clean up ifcfg files
  google_guest_agent/network/manager/network_manager_linux.go
  google_guest_agent/network/manager/network_manager_linux_test.go
Labels: lgtm, approved, size/M

#373 NetworkManager: fix ipv6 and ipv4 mode attribute
  google_guest_agent/network/manager/network_manager_linux.go
Labels: lgtm, approved, size/S

#374 network: early setup network
  google_guest_agent/instance_setup.go
  google_guest_agent/main.go
Labels: lgtm, approved, size/M

#375 address manager: make sure we check for oldMetadata
  google_guest_agent/addresses.go
Labels: lgtm, approved, size/XS

#378 NetworkManager: only set secondary interfaces as up
  google_guest_agent/network/manager/network_manager_linux.go
Labels: lgtm, approved, size/XS

#380 Fix minor typo in comment
  google_guest_agent/main.go
Labels: lgtm, approved, size/XS, ok-to-test

#372 systemd-networkd: support debian 12's version
  google_guest_agent/network/manager/systemd_networkd_linux.go
Labels: lgtm, approved, size/XS

#368 Add require-oslogin-certificates logic to disable keys
  google_guest_agent/non_windows_accounts.go
  google_guest_agent/oslogin.go
  google_guest_agent/oslogin_test.go
  metadata/metadata.go
Labels: lgtm, approved, size/L

#365 Add COS homedir-gid patch to upstream.
  google_guest_agent/accounts_unix.go
  google_guest_agent/accounts_windows.go
  google_guest_agent/non_windows_accounts.go
  google_guest_agent/windows_accounts.go
Labels: lgtm, approved, size/M, ok-to-test

#381 Update dhclient pid/lease file directory to abide apparmor rules and fix lint warnings
  google_guest_agent/network/manager/dhclient_linux.go
  google_guest_agent/network/manager/dhclient_linux_test.go
  google_guest_agent/network/manager/manager_test.go
  google_guest_agent/network/manager/systemd_networkd_linux_test.go
  google_guest_agent/network/manager/wicked_linux.go
Labels: lgtm, approved, size/M

#382 change metadata key to enable-oslogin-certificates
  google_guest_agent/oslogin_test.go
  metadata/metadata.go
Labels: lgtm, approved, size/XS

#383 All non-200 status code from MDS should raise error
  metadata/metadata.go
Labels: lgtm, approved, size/S

#384 Add more error logging in snapshot handling requests, use common retry util
  google_guest_agent/snapshot_listener.go
Labels: lgtm, approved, size/L
