Repository GoogleCloudPlatform/guest-agent, pull requests merged in 2025-02, with the labels that each got.

#491 Fix windows package build failures
  packaging/googet/windows_agent_build.sh
Labels: lgtm, approved, size/XS

#489 Include interfaces in lists even if it has an invalid MAC.
  google_guest_agent/network/manager/common.go
  google_guest_agent/network/manager/common_test.go
  google_guest_agent/network/manager/dhclient_linux.go
  google_guest_agent/network/manager/netplan_linux.go
  google_guest_agent/network/manager/network_manager_linux.go
  google_guest_agent/network/manager/systemd_networkd_linux.go
  google_guest_agent/network/manager/wicked_linux.go
Labels: lgtm, approved, size/L

#493 Add clarification to comments regarding invalid NICs and the `invalid` tag.
  google_guest_agent/network/manager/common.go
Labels: lgtm, approved, size/S

#494 vlan: move config out of unstable section
  google_guest_agent/cfg/cfg.go
  google_guest_agent/network/manager/manager.go
Labels: lgtm, approved, size/XS

#495 vlan: toggle vlan configuration in debian packaging
  instance_configs.cfg
  packaging/debian/rules
Labels: lgtm, approved, size/XS

#490 scripts: introduce a wrapper to locally build deb package
  build-deb.sh
Labels: lgtm, approved, size/M

#492 Start bundling ggactl_plugin_cleanup binary in all agent packages
  packaging/debian/prerm
  packaging/debian/rules
  packaging/googet/agent_uninstall.ps1
  packaging/googet/google-compute-engine-windows.goospec
  packaging/googet/windows_agent_build.sh
  packaging/google-guest-agent.spec
Labels: lgtm, approved, size/S

#498 Start packaging compat manager
  packaging/debian/rules
  packaging/googet/agent_install.ps1
  packaging/googet/agent_uninstall.ps1
  packaging/googet/google-compute-engine-windows.goospec
  packaging/googet/windows_agent_build.sh
  packaging/google-guest-agent.spec
Labels: lgtm, approved, size/M

#499 Update crypto library to fix CVE-2024-45337
  go.mod
  go.sum
Labels: lgtm, approved, size/S

#500 Include core plugin binary for all packages
  packaging/debian/rules
  packaging/googet/google-compute-engine-windows.goospec
  packaging/googet/windows_agent_build.sh
  packaging/google-guest-agent.spec
Labels: lgtm, approved, size/S

#501 Fix typo in windows build script
  packaging/googet/windows_agent_build.sh
Labels: lgtm, approved, size/XS
