Repository GoogleCloudPlatform/guest-agent, pull requests merged in 2025-07, with the labels that each got.

#558 Update agent_uninstall.ps1
  packaging/googet/agent_uninstall.ps1
Labels: lgtm, approved, size/XS, ok-to-test

#557 Build rollforward package to re-enable original agent and disable core plugin
  core-plugin-enabled
  packaging/debian/postinst
  packaging/debian/prerm
  packaging/debian/rules
  packaging/googet/agent_install.ps1
  packaging/googet/agent_uninstall.ps1
  packaging/googet/google-compute-engine-windows.goospec
  packaging/googet/windows_agent_build.sh
  packaging/google-guest-agent.spec
Labels: lgtm, approved, size/M

#560 Update google_metadata_script_runner_adapt for both startup/shutdown
  google-shutdown-scripts.service
  google-startup-scripts.service
  google_metadata_script_runner_adapt
Labels: lgtm, approved, size/XS
