Repository GoogleCloudPlatform/guest-agent, pull requests merged in 2025-01, with the labels that each got.

#479 Update logging library used by guest agent
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#465 Implement support for vlan dynamic removal, update dhclient to remove only if configured
  google_guest_agent/network/manager/common.go
  google_guest_agent/network/manager/common_test.go
  google_guest_agent/network/manager/dhclient_linux.go
  google_guest_agent/network/manager/dhclient_linux_test.go
  google_guest_agent/network/manager/netplan_linux.go
  google_guest_agent/network/manager/netplan_linux_test.go
  google_guest_agent/network/manager/wicked_linux.go
  utils/file.go
  utils/file_test.go
Labels: size/XL, lgtm, approved

#468 networkd(vlan): remove the interface in addition to config
  google_guest_agent/network/manager/systemd_networkd_linux.go
Labels: lgtm, approved, size/S

#482 Do not fail network setup if there is an invalid/bad MAC
  google_guest_agent/network/manager/common.go
Labels: lgtm, approved, size/XS

#487 Remove Amy and Zach from OWNERS
  OWNERS
Labels: lgtm, approved, size/XS

#488 Revert PR #482
  google_guest_agent/network/manager/common.go
Labels: lgtm, approved, size/XS

#486 vlan: don't index based on the vlan ID
  google_guest_agent/network/manager/common.go
  google_guest_agent/network/manager/common_test.go
  google_guest_agent/network/manager/dhclient_linux_test.go
  google_guest_agent/network/manager/manager.go
  google_guest_agent/network/manager/manager_test.go
  google_guest_agent/network/manager/netplan_linux.go
  google_guest_agent/network/manager/netplan_linux_test.go
  google_guest_agent/network/manager/network_manager_linux_test.go
  google_guest_agent/network/manager/systemd_networkd_linux_test.go
Labels: lgtm, approved, size/L
