Repository GoogleCloudPlatform/guest-agent, pull requests merged in 2025-05, with the labels that each got.

#524 Wicked: Only reload interfaces for which configurations are written or changed.
  google_guest_agent/network/manager/wicked_linux.go
  google_guest_agent/network/manager/wicked_linux_test.go
Labels: lgtm, approved, size/M

#533 Make NSS cache refresh asynchronous
  google_guest_agent/oslogin.go
Labels: lgtm, approved, size/S

#534 Make sure agent added connections are activated by NM
  google_guest_agent/network/manager/network_manager_linux.go
  google_guest_agent/network/manager/network_manager_linux_test.go
Labels: lgtm, approved, size/S

#535 Update core plugin path as per main branch
  packaging/debian/rules
Labels: lgtm, approved, size/XS

#537 Enable debug logging for core plugin testing
  instance_configs.cfg
Labels: lgtm, approved, size/XS
