Repository GoogleCloudPlatform/guest-agent, pull requests merged in 2025-03, with the labels that each got.

#509 Revert bundling new binaries in the package
  google-guest-agent-manager.service
  google-guest-compat-manager.service
  packaging/debian/prerm
  packaging/debian/rules
  packaging/googet/agent_install.ps1
  packaging/googet/agent_uninstall.ps1
  packaging/googet/google-compute-engine-windows.goospec
  packaging/googet/windows_agent_build.sh
  packaging/google-guest-agent.spec
Labels: lgtm, approved, size/M

#510 Update dev branch with latest changes for testing
  google-shutdown-scripts.service
  google-startup-scripts.service
  packaging/debian/rules
  packaging/googet/google-compute-engine-windows.goospec
  packaging/googet/run_shutdown_scripts.cmd
  packaging/googet/run_startup_scripts.cmd
  packaging/googet/windows_agent_build.sh
  packaging/google-guest-agent.spec
Labels: lgtm, approved, size/S

#502 Bundle new gce metadata script runner binary in agent package
  packaging/debian/rules
  packaging/googet/google-compute-engine-windows.goospec
  packaging/googet/windows_agent_build.sh
  packaging/google-guest-agent.spec
Labels: lgtm, approved, size/S

#503 Update startup/shutdown services to launch compat manager
  google-shutdown-scripts.service
  google-startup-scripts.service
  packaging/googet/run_shutdown_scripts.cmd
  packaging/googet/run_startup_scripts.cmd
Labels: lgtm, approved, size/S

#513 Bundle compat metadata script runner binary in package
  packaging/debian/rules
  packaging/googet/google-compute-engine-windows.goospec
  packaging/googet/windows_agent_build.sh
  packaging/google-guest-agent.spec
Labels: lgtm, approved, size/S

#514 Fix debian build path
  packaging/debian/rules
Labels: lgtm, approved, size/XS

#515 Fix failing builds by updating the dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/S

#517 Fix install path for core plugin
  packaging/debian/rules
Labels: lgtm, approved, size/XS

#518 Fix core plugin path
  packaging/debian/rules
Labels: lgtm, approved, size/XS

#519 Enable guest services on package upgrade
  packaging/google-guest-agent.spec
Labels: lgtm, approved, size/XS

#522 Re-enable disabled services if the core plugin was enabled
  packaging/debian/postinst
  packaging/google-guest-agent.spec
Labels: lgtm, approved, size/S

#521 Re-enable disabled services if the core plugin was enabled
  packaging/debian/postinst
  packaging/google-guest-agent.spec
Labels: lgtm, approved, size/S

#523 Revert "oslogin: Correctly handle newlines at the end of modified fil…
  google_guest_agent/oslogin.go
  google_guest_agent/oslogin_test.go
Labels: lgtm, approved, size/M

#508 Add 'created-by' metadata, and pass it as option to logging library
  gce_workload_cert_refresh/main.go
  go.mod
  go.sum
  google_authorized_keys/main.go
  google_guest_agent/main.go
  google_metadata_script_runner/main.go
  metadata/metadata.go
Labels: lgtm, approved, size/S

#526 Update guest-logging-go dependency
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#527 Remove error messages from cert refresher and metadata script runner
  gce_workload_cert_refresh/main.go
  google_metadata_script_runner/main.go
Labels: lgtm, approved, size/S
